### ISSUE TITLE
Eclipse installation issue and solution

### ISSUE THREAD

**Issue by marvin-x** [oyse/yedit#14]
Hi! I want to share an experience with the Eclipse installation of YEdit. It might be specific to my installation, but others might run into it too.

When installing through Eclipse Marketplace or update site, the installation may not continue due to a dependency on Apache Commons Lang 2.6.0.

Solution:
You would need to download the library from 
http://commons.apache.org/proper/commons-lang/download_lang.cgi
and drop the JAR (extracted from compressed file) in the plugins folder.

Restart Eclipse and check that the library is loaded through Help > About Eclipse > Instalation Details > (Tab) Plugins.
Then try to install YEdit again.

Also: maybe a link to the github wiki from Readme.creole would help as the wiki has a bit more information on requirements.

Thanks for the Plugin!

**Comment by tom-dalton-fanduel** [comment]
I've just run into the same issue when trying to install 1.0.16 from the update site. The error I get in the updater dialog:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: YEdit Feature 1.0.16 (org.dadacoalition.yedit.feature.group 1.0.16)
  Missing requirement: YEdit Feature 1.0.16 (org.dadacoalition.yedit.feature.group 1.0.16) requires 'org.apache.commons.lang 2.6.0' but it could not be found
```

I'm using Eclipse: 3.8.1

**Comment by oyse** [comment]
Hmmm, I thought I removed the dependency completely in the 1.0.16 release. It appears that it is still there for some reason.

I will look into it when I have time. Thank you for reporting the issue.

**Comment by jjjesus** [comment]
Installed yesterday (April 24, 2015) in Eclipse Luna and I didn't run into installation problems (that I noticed), but, I didn't the YAML syntax highlighting wasn't working.  After installing the Commons Lang jar, the syntax highlighting showed up, very nicely, BTW.  I don't think the version of the Commons Lang jar matters, I used 3.6.
