### ISSUE TITLE
Clarify license (EPL) on source code and/or README of the project

### ISSUE THREAD

**Issue by kdvolder** [oyse/yedit#20]
It would be nice to make a more obvious declaration of the license (I gather it is EPL) but this is only inlcuded in one place (the feature.xml). So you do see it on the marketplace or update-site install.

However, it would be nice to at least make mention of the EPL on some obvious place when visiting the github main page (i.e. mention of EPL in readme).

Also it is customary to add license comment headers on each java source file. (I know, I hate that stuff as well, but it makes things easier when corporate lawyers have to look at a project and give their okay to include it in something like STS... which is what I'd like to do :-)

There's a easy way to add CR headers to all your files using Eclipse copyright plugin (https://wiki.eclipse.org/Development_Resources/How_to_Use_Eclipse_Copyright_Tool) 

Here's a example of a file with a typical EPL header:
https://github.com/spring-projects/spring-ide/blob/master/plugins/org.springframework.ide.eclipse.boot.properties.editor.yaml/src/org/springframework/ide/eclipse/boot/properties/editor/yaml/SpringYeditSourceViewerConfiguration.java

**Comment by oyse** [comment]
I have added a standard EPL copyright notice to all the java files in branch issue-20-copyright (https://github.com/oyse/yedit/tree/issue-20-copyright)

Is that what you need?

The notice is slightly incorrect as for some files there might be other contributers, but tracking that down is a bit of work. Will that be important to you in this context?

**Comment by kdvolder** [comment]
That looks fine. I am not a lawyer. But I gather you try to make your copyright headers as accurate as you can, within reason. So you might want to consider adding a hint that there are other contributors involved. Maybe a header like this one:

http://alvinalexander.com/java/jwarehouse/eclipse/org.eclipse.core.runtime/src/org/eclipse/core/internal/preferences/legacy/InitLegacyPreferences.java.shtml

I.e. '(c) IBM Corporation and others' in the header hints that not just IBM may have a claim on the IP. If someone really wants to dig in and figure out who did what they can consult the change history in git.

For our purposes, I beleave legal wants to see a good open-source licence. EPL license is great.

**Comment by oyse** [comment]
Good point. I have added an 'and others' to the copyright notices. I have also mentioned the licenses in the README.

The changes have been merged to the development branch.
