### ISSUE TITLE
403 on http://dadacoalition.org/yedit/

### ISSUE THREAD

**Issue by gronono** [oyse/yedit#23]
http://dadacoalition.org/yedit/ is not available.

**Comment by clonedagain** [comment]
Same here

**Comment by oyse** [comment]
The update site is working, but there seems like there is no index.html file there. I have created a simple one so that at least there is no 403 message shown.

**Comment by kdvolder** [comment]
Right, technically, update sites actually don't need a index.html. Eclipse doesn't read what's actually at the update site-url itself, but only reads urls that are relative to it contains p2 metadata etc.

But adding a simple index.html can avoid lots of confusion for users who aren't aware of this technicality and point a web-browser directly at the URL.
