### ISSUE TITLE
RFE: Add support for eclipse's Task Tags (e.g. TODO)

### ISSUE THREAD

**Issue by ThomasLandauer** [oyse/yedit#24]
Right now, if I add the keyword "TODO" in a .yml file, it isn't listed in eclipse's Tasks View. I'm not sure if this is a YEdit issue at all. But it would be nice if you could integrate this - or just tell me how to activate it.

Thanks!!

**Comment by oyse** [comment]
Just to be sure that I know what you are asking for: Do you want a TODO in a Yaml **comment** to show up in the Tasks View?

**Comment by ThomasLandauer** [comment]
Yeah, exactly! :-) Something like
```
# TODO: Improve this...
```

**Comment by oyse** [comment]
An initial implementation is found in the branch issue-24-task-tags.

There is currently no preference support so only TODO and FIXME will work. 

Also it only supports a single task tag in single comment. I am not sure if there is any need for more.

Do you have time to test the feature to see if it works as you expect? Can you build the plugin your self or should I provide you with a binary?

**Comment by ThomasLandauer** [comment]
Yeah, I'd be happy to test it! :-)
But I can't build the plugin, please make a binary for Windows (I have eclipse 64 bit) available somehow.

Thanks!

**Comment by oyse** [comment]
Great. I will see if I can manage to get the preference implementation in place before I make a version for you.

**Comment by oyse** [comment]
Could you try the following plugin version?

Just put the .jar file in the plugins directory and it should work.

http://dadacoalition.org/yedit_test_plugins/org.dadacoalition.yedit_1.0.19.201508201857-SNAPSHOT.jar

I have added preference for task tags as well. Changes to the preferences are only reflected after you save a file.

**Comment by ThomasLandauer** [comment]
Works, great, thanks!! :-)

Details:
I had this file in my plugins directory: org.dadacoalition.yedit_1.0.18.201506060953-RELEASE.jar
When I *add* the new org.dadacoalition.yedit_1.0.19.201508201857-SNAPSHOT.jar it doesn't work (i.e. no change at all).
When I *remove* the old RELEASE-file (keeping only SNAPSHOT), YEdit seems to be gone alltogether. Message: "No editor descriptor for id org.dadacoalition.yedit.editor.YEdit"
Only when I *rename* the SHAPSHOT-file, giving it the RELEASE-file name, it works like this:
When I write "# TODO", the task is created as soon as I save the file.
The preference I cannot find: Under Window > Preferences > YEdit Preferences I can't see any new task preference. Don't know what this would be supposed to do - I guess it's not important for me ;-)

Thanks!!

**Comment by oyse** [comment]
Hmm, strange that the preferences did not work. I will take a look at it.

Thanks for taking the time to test the feature.

**Comment by oyse** [comment]
I have released the task tag support now. It should be available through the update site or downloadable from the release here on GitHub
