### ISSUE TITLE
Problem installing Plugin using marketplace 

### ISSUE THREAD

**Issue by edsonschleiwabion** [oyse/yedit#25]
eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/home/schlei/workspaces/all-git-projects/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.ui
Warning
Tue Jul 07 13:59:33 CEST 2015
Invalid property category path:  (bundle: net.vtst.ow.eclipse.less.ui, propertyPage: net.vtst.ow.eclipse.less.ui.properties.LessProjectPropertyPage)

An exception stack trace is not available.

**Comment by NickvL01** [comment]
I have the same problem.

**Comment by oyse** [comment]
Do you have any more information on the problem? The warning seems to be unrelated to the installation problem since it is for another plugin.

**Comment by oyse** [comment]
Can you verify if that this problem is the same as in Issue #26? Is the problem fixed now?

**Comment by edsonschleiwabion** [comment]
It is working now, it seams that it was the same Issue #26 .
