### ISSUE TITLE
Cant install plugin in marketplace

### ISSUE THREAD

**Issue by SenseiTechUS** [oyse/yedit#26]
I tried downloading the plugin via the marketplace. But an error came up saying..

The following solutions are not available: YEdit 1.0.14 (id=org.dadacoalition.yedit.feature.group, site=http://dadacoalition.org/yedit)

Any reason why? Ask if you need more info

-SenseiTechUS

**Comment by ThomasLandauer** [comment]
I get the same error message:
> The following solutions are not available: YEdit 1.0.14 (id=org.dadacoalition.yedit.feature.group, site=http://dadacoalition.org/yedit)

Eclipse Mars Release (4.5.0), Build id: 20150621-1200

**Comment by oyse** [comment]
I will take a look at it when I get the time. Hopefully within a few days.

**Comment by oyse** [comment]
I seems like there has been some change in how Marketplace handles the installation that I wasn't aware of. 

I have updated the Marketplace info and in my test everything seems to be working.

Please verify that everything is now working for you.

**Comment by ThomasLandauer** [comment]
Thank you - works for me! :-)
