### ISSUE TITLE
Upgrade required Java version to Java 7 or Java 8

### ISSUE THREAD

**Issue by oyse** [oyse/yedit#28]
Currently YEdit is written for Java 5. This is a bit of a pain and the required version should be upgrade to either Java 7 or Java 8.

@kdvolder Do you have any opinions on this?

**Comment by kdvolder** [comment]
Generally it is good to be a little on the conservative side when it comes to the JRE required to run your plugin. But yes, Java 5 is a bit old now, its okay to move on from that. 

Java 7 is probably fine. I'd wait a bit more for Java 8. Still quite a few people will be sticking on Java 7 still and you don't want to stop them from using your plugin.

A good place to take your queu from is this page: https://wiki.eclipse.org/Eclipse/Installation
You can see there that both Eclipse luna and mars require Java 7.

**Comment by oyse** [comment]
Good point. I will go with 7
