### ISSUE TITLE
Syntax warning on '@' sign

### ISSUE THREAD

**Issue by ThomasLandauer** [oyse/yedit#30]
Hi,

I get a syntax warning (exclamation mark in yellow triangle) on the last line of this file:

    services:
      gedmo.listener.timestampable:
          class: Gedmo\Timestampable\TimestampableListener
          tags:
            - { name: doctrine.event_subscriber, connection: default }
          calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

The tooltip says:
> found character @ '@' that cannot start any token. (Do not use @ for indentation)

It's the original Symfony file app/config/services.yml. In YEdit Preferences I have "Symfony compatibility mode" activated.

**Comment by oyse** [comment]
Do you get the same error if you disable the symfony mode? The symfony mode is only needed for handling %%var%% and %var%

**Comment by ThomasLandauer** [comment]
Yes, also with Symfony mode being off.

**Comment by oyse** [comment]
Looking through the YAML 1.1 spec I see that starting a plain scalar with @ is not allowed as the character is reservered for future use.

To avoid the problem you should put the scalar in single or double qoutes.

**Comment by ThomasLandauer** [comment]
Yeah, thanks, the quotes did the trick :-)
It origins (probably) from a Symfony Extension; I did a pull request there. Sorry for bothering you.

**Comment by oyse** [comment]
No problem. Glad you got it to work.
