### ISSUE TITLE
Syntax warning on ':' sign

### ISSUE THREAD

**Issue by ThomasLandauer** [oyse/yedit#31]
Hi,

I get a syntax warning (exclamation mark in yellow triangle) on the third line of this file:

    Foo:
      path: /
      defaults: { _controller: AppBundle:Foo:index }
    Foo:
      path: /
      defaults: { _controller: AppBundle:Foo:index }

The tooltip says:

    found unexpected ':'

It's a Symfony routing file. The reason are the colons in `AppBundle:Foo:index`. Oddly enough, the warning is only shown on the *first* occurrence (third line), not on the second occurrence. In YEdit Preferences I have "Symfony compatibility mode" activated.

**Comment by oyse** [comment]
Do you get the same error if you disable the symfony mode? The symfony mode is only needed for handling %%var%% and %var%

**Comment by ThomasLandauer** [comment]
Yes, also with Symfony mode being off.

**Comment by oyse** [comment]
Looking through the Yaml 1.1 spec I see that : characters are not allowed in plain scalars (look in section 9.1.3). To fix the problem you need to put the scalar in either single or double qoutes.

**Comment by ThomasLandauer** [comment]
This one is harder ;-)
The full line reads:
> defaults: { _controller: AppBundle:Foo:index, bar:null }

What should it be then?:
> defaults: { _controller: "AppBundle:Foo:index", "bar:null" }

or
> defaults: { _controller: "AppBundle:Foo:index, bar:null" }

Neither does work in Symfony ;-) But I'm going to suggest it there. Could you give me a link to the specs? Is 1.1 or 1.2 the current version?

Thanks!

**Comment by oyse** [comment]
YEdit only supports 1.1, but the differences are minor and should not effect this problem. See http://yaml.org/spec/1.1/ and http://yaml.org/spec/1.2/spec.html

> defaults: { _controller: "AppBundle:Foo:index, bar:null" }

This version looks like the correct Yaml to me, but I know nothing about Symfony so I do not know how it interprets this.

**Comment by ThomasLandauer** [comment]
Thanks, I'm closing this.
