### ISSUE TITLE
Ask for permission to redestribute

### ISSUE THREAD

**Issue by hstaudacher** [oyse/yedit#36]
Hi, 
we have created an Eclipse Plug-In to launch [Dropwizard](http://dropwizard.io) applications. One part of such applications is a config that is written in yaml. We have included the yedit plugin as a separate feature (untouched). Before I submit the plugin to the Eclipse Marketplace I would like to ask for permission to redistribute the yedit feature.

**Comment by hstaudacher** [comment]
Oh, by the way, this is plugin I'm talking about https://github.com/Tasktop/dropwizard-tools

As you can see we have added references to yedit also in the README

**Comment by oyse** [comment]
Just go ahead and re-distribute. I have no problems with that :)
