### ISSUE TITLE
Syntax error - false positive

### ISSUE THREAD

**Issue by pulse00** [oyse/yedit#4]
I'm getting a syntax error `expected ',' or '}', but got BlockEntry` in line 6 for the following yaml file:

	security: 
	    access_control: 
    
	            - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY } # for the case of a failed login
            
	            - { path: ^/user/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            
	            - { path: ^/user/check-confirmation-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }

I'm not 100% sure, but i think this should be a valid yml file.

**Comment by oyse** [comment]
This issue will not be fixed since it will break other cases. I am closing the case.
