### ISSUE TITLE
YEdit appears to cause null pointer exception crash of Oxygen

### ISSUE THREAD

**Issue by kbcmdba** [oyse/yedit#47]
When I loaded YEdit in a fresh install of Oxygen JEE, I opened one of my Ansible .yaml files and Eclipse gave me a null pointer exception within seconds. Reopening Eclipse caused the same problem seconds after it reopened. Closing the .yaml file before I restarted Eclipse again. Even after having closed the .yaml file that may have contributed to the null pointer exception, I am still getting null pointer exceptions when I open Eclipse. I didn't get any of these exceptions prior to installing YEdit.

Any suggestions/ideas?

**Comment by kdvolder** [comment]
> Any suggestions/ideas?

Do you have a stacktrace?

**Comment by kbcmdba** [comment]
Sorry guys - I don't have any details for you. I'm no longer with that company. I haven't used YEdit since then. I'm going to go ahead and close this because I just don't have enough details for you to be able to reproduce the issue.
