### ISSUE TITLE
http://dadacoalition.org/yedit is not reachable

### ISSUE THREAD

**Issue by akravets** [oyse/yedit#52]
Unable to access http://dadacoalition.org/yedit as of today, please advise.

**Comment by oyse** [comment]
I moved servers and had forgotten about the old update site. I am trying to get it up again now. It will hopefully be available in a day or two.

Thanks for reporting though the project is mostly dead.

**Comment by oyse** [comment]
Should be fixed now. According to https://www.eclipse.org/setups/marketplace/?style=all there is no error any more. Let me know if the issue still persist for you.
